#!/bin/sh
version=$(rpm -q --qf '%{version}' system-release)
cat << EOF

       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/$version-release-notes/
EOF
